name: Wake Up Streamlit Apps

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

concurrency:
  group: wake-streamlit
  cancel-in-progress: true

jobs:
  wake-up:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install Chromium & ChromeDriver
        run: |
          sudo apt-get update

          sudo apt-get install -y \
            chromium-browser \
            chromium-chromedriver

          which chromium-browser
          which chromedriver

      - name: Install Python dependencies
        run: |
          pip install selenium

      - name: Run wake script
        run: python wake_up_streamlit.py

      - name: Show logs
        run: |
          echo "=========== LOGS ==========="
          cat wakeup_log.txt

      - name: Upload log file
        uses: actions/upload-artifact@v5
        with:
          name: wakeup-log
          path: wakeup_log.txt
          retention-days: 1
